name: Action for 3 jobs
on:
  push:
    branches: [ "main" ]
jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello
      run: echo "Hello!"
    - name: Print version ubuntu
      run: lsb_release -a
    - name: Print sha- of commit
      run: git clone https://github.com/m1dros/gitex.git && git log --oneline
  
