name: Action for 3 jobs
env:
  COMMITNAME : Commit-name-${{ github.sha }}
on:
  push:
    branches: [ "main" ]
jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello
      run: |
        echo "Hello!"
        lsb_release -a
        echo "Its is ${{ env.COMMITNAME }}"
  
